version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

  db-init:
    build: .
    command: ["/usr/src/app/wait-for-it.sh", "db:3306", "--timeout=60", "--", "npm", "run", "initdb"]
    depends_on:
      - db
    environment:
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: db
      MYSQL_PORT: 3306

  api:
    build: .
    command: ["/usr/src/app/wait-for-it.sh", "db:3306", "--timeout=60", "--", "npm", "start"]
    depends_on:
      - db
    environment:
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app

volumes:
  db-data: